### ISSUE TITLE
Comparison with mobx-state-tree ?

### ISSUE THREAD

**Issue by redbar0n** [mfellner/valtio-factory#3]
Could you compare and contrast valtio-factory with mobx-state-tree (MST) ?
I'm not familiar with either, and I find it hard to discern them.

Specifically curious what you found lacking in MST which inspired you to create valtio-factory ?

**Comment by mfellner** [comment]
Thanks for the question!

> ... valtio, which simplifies proxy state. think of something like mobx, now remove 99% of the api surface.
> [0xca0a · Nov 17, 2020](https://twitter.com/0xca0a/status/1328742919872933888)

Some of the general motivation behind this library can be found in the [README](https://github.com/mfellner/valtio-factory#motivation) and a [discussion post](https://github.com/pmndrs/valtio/discussions/348) on the original valtio repository.

MST was the inspiration behind the API design but also the reason why I wrote the library in the first place. In fact, I started a React Native project based on Infinite Red's [ignite](https://github.com/infinitered/ignite) template, which uses MST, and found working with it frustrating. Some of the issues I had with MST were:

- too much boilerplate declaring [models](https://mobx-state-tree.js.org/concepts/trees) (especially when already using TypeScript)
- even more boilerplate declaring TypeScript types for models ([example](https://github.com/infinitered/ignite/blob/v7.15.0/boilerplate/app/models/character-store/character-store.ts#L33-L36))
- ["subscriptions"](https://mobx-state-tree.js.org/concepts/listeners) fall back on regular MobX (not part of the MST model declaration)

On the other hand, MST comes with advanced features that valtio doesn't have and it's based on MobX which has even more features. Some advanced MST features:

- [patches](https://mobx-state-tree.js.org/concepts/patches)
- [middleware](https://mobx-state-tree.js.org/concepts/middleware)
- [volatile state](https://mobx-state-tree.js.org/concepts/volatiles)
- [async actions](https://mobx-state-tree.js.org/concepts/async-actions) with generators (not typesafe!)

So to summarise, I'd say MST's downsides are boilerplate, not playing too well with TypeScript, and overall complexity. However MST and MobX have more features and are more powerful than valtio and valtio-factory.

valtio-factory's strength is being a simple add-on on top of the even simpler valtio library, providing a nice sweet spot between complexity and simplicity, in my opinion.

The other pmndrs state libraries [jotai](https://github.com/pmndrs/jotai) and [zustand](https://github.com/pmndrs/zustand) are are also extremely simplistic. I recommend checking them out. Actually, some people like to organise "modern" React state management libraries into the following categories:

- Flux (Redux, Zustand)
- Proxy (Mobx, Valtio)
- Atomic (Recoil, Jotai)

> https://blog.logrocket.com/jotai-vs-recoil-what-are-the-differences

Another dimension to add would be "complexity", where valtio-factory sits somewhere between MST and vanilla valtio. I hope my answer provides a better understanding of where valtio-factory lives in this big picture and what tradeoffs you might consider.

**Comment by redbar0n** [comment]
Thanks for a fantastic  (thorough) answer! :D <3 It made a lot of sense!
